server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE

  config:
    import: optional:configserver:http://localhost:8085

  datasource:
    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/microservicesRating
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true


#eureka:
#  instance:
#    prefer-ip-address: true
##      hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

